inputflags:
    access.sequential


outputflags:
    temp


rule all:
    input:
        "test3.out"


rule a:
    output:
        "test1.out"
    shell:
        "echo test > {output}"


rule b:
    input:
        "test1.out"
    output:
        "test2.out"
    group: "test"
    shell:
        "cp {input} {output}"


rule c:
    input:
        "test2.out"
    output:
        "test3.out"
    group: "test"
    shell:
        "cp {input} {output}"