from snakemake.utils import min_version

min_version("6.1.1")

configfile: "config.yaml"

remote_snakefile = "https://raw.githubusercontent.com/snakemake/snakemake/v6.1.1/tests/test_script_py/Snakefile"

module with_script:
    snakefile:
        remote_snakefile
    config:
        config

use rule * from with_script as with_script_*

rule all:
    input:
        rules.with_script_all.input
