from snakemake.remote.FTP import RemoteProvider as FTPRemoteProvider

FTP = FTPRemoteProvider(username="user", password="pass")

rule all:
    input:
        "output.txt",
        "output.txt.bz2"

rule step1a:
    input: FTP.remote("ftp-private.ebi.ac.uk/upload/snakemake/input.txt")
    output: pipe("out_1a.txt")
    shell:
        """
        cat {input} > {output}
        """

rule step1b:
    input: "out_1a.txt"
    output: temp("out_1b.txt")
    resources:
        mem_mb=1000,
        disk_mb=1000,
        _cores=2,
    shell:
        """
        cat {input} > {output}
        """

rule step1c:
    output: temp("out_1c.txt")
    params:
        message="hello world"
    resources:
        mem_mb=2000,
        disk_mb=2000,
        _cores=4,
    script: "scripts/test_script.py"

rule step1d:
    output: temp("out_1d.txt")
    params:
        message="hello world"
    run:
        with open(output[0], "w") as f:
            f.write(params.message)

rule step2:
    input:
        "out_1b.txt",
        "out_1c.txt",
        "out_1d.txt"
    output:
        "output.txt",
        "output.txt.bz2"
    conda:
        "envs/gzip.yaml"
    log: "test.log"
    shell:
        """
        cat {input[0]} >> {output[0]}
        cat {input[1]} >> {output[0]}
        cat {input[2]} >> {output[0]}
        bzip2 -c {output[0]} > {output[1]}
        echo "fine" > {log} 
        """
