from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider

shell.executable("bash")

HTTP = HTTPRemoteProvider()

shell("touch C && sleep 1 && touch B && sleep 1 && touch A && touch D && \
    mkdir -p github.com/snakemake/snakemake/raw/main/tests/test_remote_http/expected-results && \
    touch github.com/snakemake/snakemake/raw/main/tests/test_remote_http/expected-results/landsat-data.txt && \
    touch -t 200101010101 old_file")

#Will not be executed even though A is newer (A is treated as ancient)
rule a:
    input:
        "A"
    output:
        "B"
    shell:
        "echo \"B recreated\" > {output}"

#Will not be executed even though B is newer (B is treated as ancient)
rule b:
    input:
        "B"
    output:
        "C"
    shell:
        "echo \"C recreated\" > {output}"

# Will not be executed even though C is newer (C is treated as ancient)
rule c:
    input:
        "C"
    output:
        "D"
    shell:
        "echo \"D recreated\" > {output}"

# This should not run even though output is older than input
rule remote_ancient:
    input: HTTP.remote("github.com/snakemake/snakemake/raw/main/tests/test_remote_http/expected-results/landsat-data.txt")
    output: "old_file"
    shell: "cp {input} {output}"
