rule all:
    input:
        "new_results/res.txt",
    output:
        "res.txt",
    shell:
        """
        cp {input} {output}
        echo "final" >> {output}
        """




module A:
    snakefile:
        "A.smk"
    prefix:
        "new_results"


use rule * from A as A_*


A.a = "????"


use rule t1 from A as A_t1 with:
    input:
        file="b.txt",


use rule t2 from A as A_t2 with:
    input:
        file=rules.A_t1.output.res,
        file2="c.txt",
