
from snakemake.utils import report

rule report:
	input: "Snakefile"
	output: "report.html"
	run:
		report("""
		======================
		Report of some project
		======================

		Some text containing a formula
		:math:`\sum_{{j \in E}} t_j \leq I`
		and embedding a table F1_ and a figure F2_.

		Additionally you can of course include inline tables:

		========= ====== =====
		Merged header
		----------------------
		Parameter Value  Other
		========= ====== =====
		kmer      3      foo
		iteration 4      bar
		========= ====== =====
		

		test
		""", output[0], F1=input[0], F2=input[0])
