scattergather:
    split={"items": 4, "tolerance": 0.5}


rule all:
    input:
        "gathered/all.txt",
        "external.txt"


rule split:
    output:
        scatter.split("splitted/{scatteritem}.txt")
    shell:
        r"""
        mkdir -p splitted
        for output in {output}; do
            printf '%s\n' "$output" | sed 's#^splitted/##; s#\.txt$##' > "$output"
        done
        """


rule intermediate:
    input:
        "splitted/{scatteritem}.txt"
    output:
        "splitted/{scatteritem}.post.txt"
    shell:
        r"""
        # Fail only one branch (within the tolerance allowance).
        # But the failed branch produces an output which is
        # required by a rule outside the scatter-gather process.
        case "{input}" in
            *2-of-4.txt)
                exit 1
                ;;
        esac
        cp {input} {output}
        """


rule external_rule:
    input:
        "splitted/2-of-4.post.txt"
    output:
        "external.txt"
    shell:
        "touch {output}"


rule gather:
    input:
        gather.split("splitted/{scatteritem}.post.txt")
    output:
        "gathered/all.txt"
    shell:
        "mkdir -p gathered && cat {input} > {output}"
