shell.executable("bash")

rule all:
    input:
        expand("test.out", i=range(3))

rule a:
    output:
        "test.out"
    conda:
        "test-env.yaml"
    shell:
        """
        if [ -f $CONDA_PREFIX/test.txt ] ;then
            touch {output}
        fi
        """