rule third:
    input:
        "ancient_file",
        "ancient_derivative"
    output: "result"
    shell: "touch {output}"

rule second:
    input: ancient("ancient_file")
    output: "ancient_derivative"
    shell: "touch {output}"

rule first:
    output: "ancient_file"
    shell: "touch {output}"
