from snakemake.remote.FTP import RemoteProvider as FTPRemoteProvider    
FTP = FTPRemoteProvider()    
    
rule all:    
    input:    
        "robots.txt"

FTP_URL = \
    "ftp://ftp.ensembl.org/robots.txt"
    
rule get_fasta_ftp:    
    input:    
        FTP.remote(FTP_URL, keep_local=True)    
    output:    
        "robots.txt"
    shell:    
        "mv {input:q} {output:q}"    

