from snakemake.remote.FTP import RemoteProvider as FTPRemoteProvider    
FTP = FTPRemoteProvider()    
    
rule all:    
    input:    
        "robots.txt"

FTP_URL = \
    "ftp://ftp.ensembl.org/pub/release-100/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz"
    
rule get_fasta_ftp:    
    input:    
        FTP.remote(FTP_URL, keep_local=True)    
    output:    
        "robots.txt"
    shell:    
        "mv {input:q} {output:q}"    

