shell.executable("bash")


configfile: "config/config.yaml"

for module_name, use_as in zip(["module1", "module2"], ['use_as_1', 'use_as_2']):
    module:
        name: module_name
        snakefile:
            f"{module_name}/Snakefile"
        config:
            config
        replace_prefix:
            {"results/": "results/testmodule/"}

use rule * from module1 as test1*
use rule * from module2 as test2*

rule all:
    input:
        multiext(expand("results/testmodule/c1/{name}.", name="test")[0], "tsv", "txt"),
        multiext(expand("results/testmodule/c2/{name}.", name="test")[0], "tsv", "txt"),


assert module1.some_func() == 15
assert module2.some_func() == 25
