from snakemake.utils import min_version

min_version("6.1.1")

configfile: "config.yaml"


# import 1
module first:
    snakefile:
        github("snakemake-workflows/dna-seq-varlociraptor", path="workflow/Snakefile", tag="v5.0.2")
    replace_prefix:
        {
            "benchmarking/": "benchmarking/first/",
            "logs/": "logs/first/",
            "results/": "results/first/",
            "resources/": "resources/first/",
        }
    config:
        config

use rule * from first as first_*

rule all:
    input:
        rules.first_all.input
