configfile: "config.yaml" # does not exist, but this statement should be ignored on module import


def some_func():
    return 15


rule a:
    output:
        "results/test.out"
    shell:
        "echo {config[test]} > {output}"