pepfile: "pep/config.yaml"
pepfile: "pep/config.yaml" # test overwriting

pepschema: "workflow/schemas/pep.yaml"

rule all:
    input:
        expand("{sample}.txt", sample=pep.sample_table["sample_name"])

rule a:
    output:
        "{sample}.txt"
    shell:
        "touch {output}"
