configfile: "config.yaml"  # does not exist, but this statement should be ignored on module import

rule a:
    input:
        storage.http("https://raw.githubusercontent.com/snakemake/snakemake/main/LICENSE.md"),
    output:
        "results/test.out",
    shell:
        "exit 1"  # this will trigger the onerror handler

onstart:
    with open("onstart_module1.log", "w") as f:
        f.write("This is the module1 onstart\n")

onsuccess:
    with open("onsuccess_module1.log", "w") as f:
        f.write("This is the module1 onsuccess\n")

onerror:
    with open("onerror_module1.log", "w") as f:
        f.write("This is the module1 onerror\n")
    