configfile: "config/config.yaml"

# declare https://github.com/snakemake-workflows/dna-seq-varlociraptor as a module
module dna_seq_varlociraptor:
    snakefile: 
        github(
            "snakemake-workflows/dna-seq-varlociraptor",
            path="workflow/Snakefile",
            tag="v5.16.0",
        )
    config:
        config


# import all rules
use rule * from dna_seq_varlociraptor as calling_*

# make trivial change to one of the rules
use rule delly from dna_seq_varlociraptor as calling_delly with:
    threads: 1
