shell.executable("bash")


configfile: "config/config.yaml"


module:
    snakefile:
        "module-test/Snakefile"
    config:
        config
    replace_prefix:
        {"results/": "results/testmodule/"}


use rule * from test as test_*


rule all:
    input:
        multiext(expand("results/testmodule/c/{name}.", name="test")[0], "tsv", "txt"),


assert test.some_func() == 15
