shell.executable("bash")

configfile: "config/config.yaml"


module test:
    snakefile:
        "module-test/Snakefile"
    config:
        config
    replace_prefix:
        {"results/": "results/testmodule/"}


use rule * from test as test_*

assert test.some_func() == 15
