rule all:
    input:
        "test3.x.out",
        "test3.y.out"

rule a:
    output:
        "test.out"
    shell:
        "echo test > {output}"


rule b:
    input:
        "test.out"
    output:
        "test2.out"
    shell:
        "echo test2 > {output}"


rule c:
    input:
        "test2.out",
        "test.out"
    output:
        "test3.{w}.out"
    params:
        a=config["a"]
    shell:
        "echo test3 {params.a} > {output}"
