from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider

HTTP = HTTPRemoteProvider()


rule compare:
    input:
        "landsat-data.txt",
        "landsat-data-unzipped.txt"
    shell:
        "diff {input[0]} {input[1]}"


rule copy:
    input:
        HTTP.remote("bitbucket.org/HenningTimm/snakemake-fork/raw/http-gzip-autodecode/tests/test_remote_http/expected-results/landsat-data.txt")
    output:
        "landsat-data.txt"
    shell:
        "cp {input} {output}"


rule copy_gz:
    input:
        HTTP.remote("bitbucket.org/HenningTimm/snakemake-fork/raw/http-gzip-autodecode/tests/test_remote_http/expected-results/landsat-data.txt.gz")
    output:
        "landsat-data.txt.gz"
    shell:
        "cp {input} {output}"


rule unizp:
    input:
        "landsat-data.txt.gz"
    output:
        "landsat-data-unzipped.txt"
    shell:
        "gunzip -c {input} > {output}"
