rule all:
    input:
        "c.txt"

rule a2b:
    input:
        "a.txt"
    output:
        "b.txt"
    conda:
        config["env_path"]
    script:
        "script.py"

rule b2c:
    input:
        "b.txt"
    output:
        "c.txt"
    conda:
        config["env_path"]
    script:
        "script.py"
