#!/bin/bash
if [[ ! -z "$SNAKEMAKE_PROFILE" ]]; then
    >&2 echo "SNAKEMAKE_PROFILE should not be set"
    exit 1
fi
echo `date` >> qsub.log
tail -n1 $1 >> qsub.log
# simulate printing of job id by a random number
echo $RANDOM
cat $1 >> qsub.log
sh $1
