singularity: "docker://bash"

rule a:
    singularity:
        None
    output:
        "test.out"
    shell:
        'if [ -d "/.singularity.d/" ]; then echo "In Singularity" > {output}; else echo "Not in Singularity" > {output};  fi'
