version: 2
jobs:
  build:
    machine: true
    environment:
      - GCLOUD: /opt/google-cloud-sdk/bin/gcloud
      - GSUTIL: /opt/google-cloud-sdk/bin/gsutil
      - BOTO_CONFIG: /dev/null
    steps:
      - checkout
      - restore_cache:
          keys:
            - snakemake-{{ .Environment.CACHE_VERSION }}-{{ checksum ".circleci/setup.sh" }}-{{ checksum "test-environment.yml" }}-{{ checksum ".circleci/common.sh" }}
      - run:
          name: Update PATH
          command: echo 'export PATH="`pwd`/miniconda/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Setup Conda+Singularity
          command: .circleci/setup.sh
      - save_cache:
          key: snakemake-{{ .Environment.CACHE_VERSION }}-{{ checksum ".circleci/setup.sh" }}-{{ checksum "test-environment.yml" }}-{{ checksum ".circleci/common.sh" }}
          paths:
            - miniconda
            - /usr/local
      - run:
          name: Check formatting
          command: |
            source activate black
            black --check snakemake || echo "Please run 'black snakemake'."
      - run:
          name: Setup Snakemake
          command: |
            source activate snakemake
            pip install -e .
      - run:
          name: Setup iRODS Docker image
          command: |
            docker build -t irods-server tests/test_remote_irods
            docker run -d -p 1247:1247 --name provider irods-server -i run_irods
            sleep 10
            docker exec -u irods provider iput /incoming/infile
            cp -r tests/test_remote_irods/setup-data ~/.irods
      - run:
          name: Setup gcloud
          command: |
            # skip if key is unset
            if [ -z $GCLOUD_SERVICE_KEY ]; then exit 0; fi
            # otherwise init cloud
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            sudo $GCLOUD components install kubectl
            sudo chown -R $USER:$USER /home/circleci/.config/gcloud
            $GCLOUD auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            $GCLOUD config set project snakemake-testing
      - run:
          name: Run tests
          no_output_timeout: 60m
          command: |
            export GCLOUD_CLUSTER=t-`uuidgen`
            export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json
            source activate snakemake
            py.test tests/test*.py -v -x
