
rule a:
    input:
        "test-remote-bucket/test.in"
    output:
        "test.out"
    group: "test"
    shell:
        "[[ '{resources.mem_mb}' == '1000' ]] && touch {output}"

rule b:
    output:
        "test-remote-bucket/test.in"
    group: "test"
    shell:
        "[[ '{resources.mem_mb}' == '1000' ]] && touch {output}"
