
rule a:
    input:
        "test-remote-bucket/test.in"
    output:
        "test.out"
    group: "test"
    shell:
        """
            [[ '{resources.mem_mb}' == '1000' ]] && \\
            [[ '{resources.mem}' == '1 GB' ]] && \\
            [[ '{resources.mem_mib}' == '954' ]] && \\
            touch {output}
        """

rule b:
    output:
        "test-remote-bucket/test.in"
    group: "test"
    shell:
        """
            [[ '{resources.disk_mb}' == '1000' ]] && \\
            [[ '{resources.disk}' == '1 GB' ]] && \\
            [[ '{resources.disk_mib}' == '954' ]] && \\
            touch {output}
        """
