from snakemake.remote.S3Mocked import RemoteProvider as S3RemoteProvider

s3 = S3RemoteProvider()

rule a:
    input:
        s3.remote("test-remote-bucket/test.in")
    output:
        "test.out"
    shell:
        "[[ '{resources.mem_mb}' == '1000' ]] && touch {output}"

rule b:
    output:
        s3.remote("test-remote-bucket/test.in")
    shell:
        "[[ '{resources.mem_mb}' == '1000' ]] && touch {output}"