from pathlib import Path

# File with rw access
assert choose_file(["foo", "~/.bashrc"]) == Path("~/.bashrc").expanduser()
# Folder with rwx access
assert choose_folder(["/proc", "~"]) == Path("~").expanduser()
# First is non-existing and not creatable
assert choose_tmp(["/non/existing/path", "/tmp"]) == Path("/tmp")
# First is non-existing but creatable
assert choose_tmp(["non/existing/path", "/tmp"]) == Path("non/existing/path")
# None is valid
assert choose_tmp(["/non/existing/path", "/foo"]) == "system_tmpdir"
# Folder with rwx or creatable
assert (
    choose_f(
        ["/non/existing/path", "/foo", "/bar"],
        read=True,
        write=True,
        execute=True,
        creatable=True,
    )
    is None
)


rule a:
    input:
        "test2.txt",
    output:
        "test.txt",
    shell:
        "echo {resources.tmpdir} > {output}"


rule b:
    output:
        "test2.txt",
    shell:
        "echo {resources.tmpdir} $TMPDIR $TEMP $TMP $TEMPDIR > {output}"
