shell.executable("bash")

configfile: "config/config.yaml"


rule all:
    input:
        expand("results/{w}.out", w="test")


module test:
    snakefile:
        "module-test/Snakefile"
    config:
        config
    replace_prefix: 
        {"results/": "results/testmodule/"}


use rule * from test

assert test.some_func() == 15
