shell.executable("bash")


configfile: "config/config.yaml"


module test:
    snakefile:
        "module-test/Snakefile"
    config:
        config
    replace_prefix:
        {"results/": "results/testmodule/"}


use rule * from test as test_*


rule all:
    input:
        expand(rules.test_rule_a.output, name="test"),
    default_target: True


assert test.some_func() == 15
