rule a:
    input:
        "test.in"
    output:
        "test.out"
    run:
        with open("test.in") as f:
            with open("test.out", "w") as out:
                print(resources.slurm_extra, file=out)