
rule redirect_output:
    output: "output.txt"

    log: stdout="output.log", stderr="output.err"
    shell: """touch {output}
      echo stdout log >> /dev/stdout
      echo stderr log >> /dev/stderr
      """


rule redirect_output_combine:
    output: "combined.txt"

    log: std="output.log"
    shell: """touch {output}
      echo stdout log >> /dev/stdout
      echo stderr log >> /dev/stderr
      """


rule two_stdouts:
    output: "two_stdouts.txt"
    log: std=["output.log", "other.log"]
    shell: """touch {output}
      echo stdout log >> /dev/stdout
      echo stderr log >> /dev/stderr
      """
