# a docker image based on Ubuntu with snakemake installed
FROM continuumio/anaconda
MAINTAINER Johannes Köster <johannes.koester@tu-dortmund.de>
RUN conda env update --file environment.yml --name root
