storage:
    provider="s3",
    retries=5


storage web:
    provider="http"


rule all:
    input:
        storage.s3(f"{config['s3_prefix']}/test2.out")


rule a:
    input:
        gg=storage("https://www.google.com"),
        gg2=storage.web("https://www.google.com")
    output:
        storage.s3(f"{config['s3_prefix']}/test.out")
    shell:
        "cp {input.gg} {output}"


rule b:
    input:
        rules.a.output[0]
    output:
        storage.s3(f"{config['s3_prefix']}/test2.out")
    shell:
        "cp {input} {output}"

