from snakemake.remote.GenBank import RemoteProvider as GenBankRemoteProvider
GenBank = GenBankRemoteProvider(email="someone@example.com") # email required by NCBI to prevent abuse

rule all:
    input:
        "sizes.txt"

rule download_and_count:
    input:
        GenBank.remote("KY785484.1.fasta", db="nuccore")
    output:
        "sizes.txt"
    run:
        shell("wc -c {input} > sizes.txt")
