rule all:
    input:
        o='output.txt'

rule add_dummy_package:
    output:
        o='input.txt'
    conda:
        'test_prebuilt_conda_script'
    shell:
        'touch input.txt\n'
        'python -m pip install ./dummy_package'

rule test_prebuilt_conda_script:
    input:
        i='input.txt'
    output:
        o='output.txt'
    conda:
        'test_prebuilt_conda_script'
    script:
        'test.py'
