localrules: all

shell.executable('bash')

rule all:
	input: '.done'

rule fails_sometimes:
	output:
		'.done'
	shell:
		r"""
		if [[ ! -f ".first" ]]; then
			touch .first
			exit 1
		else
			touch .done
		fi
		"""
