# vim: ft=python
from pathlib import Path


configfile: "config.yaml"


rule all:
    input:
        "perl.out",
        "perl_arguments.out",


rule perl:
    input:
        "test2.in",
        named="test.in",
    output:
        "{rulename}{empty}.out",
    log:
        "{rulename}{empty}.log",
    wildcard_constraints:
        rulename="perl",
        empty="()",
    conda:
        "envs/perl.yaml"
    resources:
        mem_mb=1024,
    params:
        integer=123,
        astring="foo\n'\\\" ",  # nasty string
        alist=["a", "b"],
    script:
        "scripts/test.pl"


rule perl_arguments:
    input:
        "test.txt",
    output:
        "perl_arguments.out",
    log:
        "perl_arguments.log",
    conda:
        "envs/perl.yaml"
    params:
        opts="--foo --bar --min=12 --max=50",
    script:
        "scripts/test_arguments.pl"
