# vim: ft=python
from pathlib import Path


configfile: "config.yaml"

rule all:
    input:
        "perl.out"


# rule mini_perl:
#     # input:
#     #     "test2.in",
#     #     named="test.in",
#     output:
#         "perl_mini.out"
#     conda:
#         "envs/perl.yaml"
#     script:
#         "scripts/test.pl"


rule perl:
    input:
        "test2.in",
        named="test.in",
    output:
        "{rulename}{empty}.out"
    wildcard_constraints:
        rulename = "perl",
        empty = "()",
    params:
        integer=123,
        astring="foo\n'\\\" ", # nasty string
        alist=["a", "b"],
    resources:
        mem_mb=1024
    log:
        "{rulename}{empty}.log"
    conda:
        "envs/perl.yaml"
    script:
        "scripts/test.pl"
