rule all:
    input:
        [
         "aligned_and_sort/1.txt",
         "aligned_and_sort/2.txt",
         "aligned_and_sort/3.txt",
         "aligned_and_sort/4.txt",
         "aligned_and_sort/5.txt",
         "aligned_and_sort/6.txt",
        ]


checkpoint trimming:
    output:
        "trimmed/{sample}.txt"
    shell:
        "touch {output}; sleep 1"


rule align:
    input:
        "trimmed/{sample}.txt"
    output:
        pipe("aligned/{sample}.txt")
    shell:
        "touch {output}; sleep 1"


rule sort:
    input:
        "aligned/{sample}.txt"
    output:
        "aligned_and_sort/{sample}.txt"
    shell:
        "touch {output}; sleep 1"
