from dataclasses import dataclass

@dataclass
class MyType:
    some_threshold: float
    filestems: list[str]

    def list_files(self, dir):
        dir = Path(dir)
        for f in self.filestems:
            yield dir / f


rule all:
    input:
        "direct1.txt",
        "reduced2.txt"


# generate typed output
checkpoint a:
    output:
        outdir=directory("something/{dataset}"),
        meta=typed("metadata/{dataset}.json", MyType)
    params:
        l="{dataset}"
    run:
        shell("mkdir -p {output.outdir}")
        shell("cd {output.outdir} && touch a b c")
        filestems = [i.stem for i in Path(output.outdir).iterdir()]
        output.meta.dump(some_threshold=0.3, filestems=filestems)


# access typed output directly
rule b:
    input:
        meta=rules.a.output.meta,
    output:
        "direct{dataset}.txt"
    run:
        val = input.meta.load().some_threshold
        assert isinstance(input.meta, str)
        shell("echo {val} {input.meta} > {output}")


# process individual items
rule c:
    output:
        touch("processed/{dataset}/{item}.txt")


# scatter over items in the typed output
def get_processed(wildcards):
    out = checkpoints.a.get(**wildcards).output
    meta = out.meta.load()
    yield from meta.list_files(out.outdir)


rule d:
    input:
        get_processed
    output:
        "reduced{dataset}.txt"
    shell:
        "ls {input} > {output}"
