TEST = "abc"

rule rule1:
	''' This rule creates an intermediate file. '''
	input: 
		'test.inter'
	output: 'test.out'
	message: 'Copying {input[0]} to {output[0]}'
	shell: 
		'echo {TEST}; cp {input[0]} {output[0]}'

rule rule2:
	input: 'test.in'
	output: 'test.inter'
	message: 'Copying {input[0]} to {output[0]}'
	shell:
		'cp {input[0]} {output[0]}'

# this should be ignored since test.in is present
rule rule3:
	input: "{a}.out"
	output: "{a}.in"
	shell: "cp {input} {output}"
