from snakemake.remote.XRootD import RemoteProvider as XRootDRemoteProvider

XRootD = XRootDRemoteProvider(use_remote=True)

remote_path = 'root://eospublic.cern.ch//eos/opendata/lhcb/MasterclassDatasets/'
my_files, = XRootD.glob_wildcards(remote_path+'D0lifetime/2014/mclasseventv2_D0_{n}.root')

rule all:
    input:
        XRootD.remote(expand('output/mclasseventv2_D0_{n}.root', n=my_files))

rule split:
    input:
        XRootD.remote(remote_path+'D0lifetime/2014/mclasseventv2_D0_{n}.root')
    output:
        XRootD.remote('output/mclasseventv2_D0_{n}.root')
    shell:
        'xrdcp {input[0]} {output[0]}'
