configfile: "config.yaml"  # does not exist, but this statement should be ignored on module import


def some_func():
    return 15


rule a:
    output:
        temp("results/a/{name}.out"),
    shell:
        "echo {config[test]} > {output}"


rule b:
    input:
        expand(rules.a.output, name="test"),
    output:
        "results/b/{name}.out",
    shell:
        "cat {input} > {output}"


rule c:
    input:
        expand(rules.b.output, name="test"),
    output:
        "results/b/{name}.out",
    shell:
        "cat {input} > {output}"


rule all:
    input:
        expand(rules.c.output, name="test"),
