configfile: "config.yaml"  # does not exist, but this statement should be ignored on module import


def some_func():
    return 15


rule rule_a:
    output:
        temp("results/{name}.out"),
    shell:
        "echo {config[test]} > {output}"


rule all:
    input:
        expand(rules.rule_a.output, name="test"),
