shell.executable("bash")

rule all:
	input: a=dynamic("test.{n}.{bla}.out"), b=dynamic("test.{n}.{bla}.csv")
	run:
		print(input.b)

rule inter:
	input: "test.{n}.{bla}.inter"
	output: "test.{n}.{bla}.out"
	shell: "cp {input} {output}"

rule dynoutput:
	input: "test.xy.in"
	output: dynamic("test.{n}.{bla}.inter")
	shell: "for i in {{0..2}}; do touch test.0$i.xy.inter; done"

rule:
	input: "test.{n}.{bla}.inter"
	output: "test.{n}.{bla}.txt"
	shell: "touch {output}"

rule:
	input: "test.{n}.{bla}.txt"
	output: "test.{n}.{bla}.csv"
	shell: "cp {input} {output}"
