

singularity: "docker://condaforge/miniforge3:26.3.2-3"


rule a:
    output:
        "test.out"
    conda:
        "test-env.yaml"
    shell:
        "grep -q '/.udocker/' /proc/self/mountinfo 2> /dev/null; "
        "bwa 2> {output} || true"
