

singularity: "docker://condaforge/miniforge3:26.3.2-3"


rule a:
    output:
        "test.out"
    conda:
        "test-env.yaml"
    shell:
        "ls /singularity; " # this fails if not in singularity container
        "bwa 2> {output} || true"
