from snakemake.remote import GS
import google.auth
try:
    GS = GS.RemoteProvider()

    rule copy:
        input:
            GS.remote(config["url"], user_project=config["project"])
        output:
            "landsat-data.txt"
        shell:
            "cp {input} {output}"
except google.auth.exceptions.DefaultCredentialsError:
    # ignore the test if not authenticated
    print("skipping test_remote_gs because we are not authenticated with gcloud")
