import os

os.environ["WORKFLOW_CONFIG"] = "workflow-config.yaml"
os.environ["TMPDIR_SUBFOLDER"] = "test"


rule:
    shell:
        "python -m snakemake --cores 3 --profile specific_profile.yaml -s Snakefile.internal"
