

rule all:
    input: "test.out"


rule a:
    output: "{sample,.+}.in"
    shell:  "touch {output}"


rule b:
    input:  rules.a.output
    output: "{sample}.inter"
    shell:  "touch {output}"


rule c:
    input:  rules.a.output
    output: "{sample}.inter"
    shell:  "exit 1"


rule d:
    input:  rules.b.output
    output: "{sample}.out"
    shell:  "touch {output}"
