rule a:
    output:
        "test.txt",
    retries: 3
    resources:
        shouldfail=lambda w, attempt: attempt < 3,
    params:
        shouldfail=lambda w, attempt: attempt < 3,
    run:
        if resources.shouldfail and params.shouldfail:
            raise ValueError("not enough attempts")
        with open(output[0], "w") as out:
            print("test", file=out)
