localrules: all, clean

rule all:
     input: "pi.calc"

rule clean:
     shell: "rm -f pi.calc"

rule compile:
     input: "pi_MPI.c"
     output: temp("pi_MPI")
     resources:
        mem_mb=0,
     shell: 
         'mpicc -o {output} {input}'

rule calc_pi:
     input: "pi_MPI"
     output: "pi.calc"
     resources:
        mem_mb=0,
           tasks=2,
           mpi='srun',
     shell: "{resources.mpi} {input} &> {output}"
