localrules: all, clean

rule all:
     input: "pi.calc"

rule clean:
     shell: "rm -f pi.calc"

rule compile:
     input: "pi_MPI.c"
     output: temp("pi_MPI")
     log:
         "logs/compile.log"
     resources:
        mem_mb=0,
        account='slurm'
        partition='compute'
     shell: 
         'mpicc -o {output} {input} &> {log}'

rule calc_pi:
     input: "pi_MPI"
     output: "pi.calc"
     resources:
        mem_mb=0,
        tasks=2,
        mpi='srun',
        account='slurm'
        partition='compute'
     shell: "{resources.mpi} {input} &> {output}"
