shell.executable("bash")

PREFIX = "SID23454678"
mid = ".t"

rule unit1:
    output:
        f"{PREFIX}{mid}xt",
    shell:
        "echo '>'{output}'<'; touch {output}; sleep 1"


rule unit2:
    shell:
        f"ls"

assert (
    f"""
{
  "hello, snakemake"
}
"""
    == """
hello, snakemake
"""
)
assert (
    f"""
    {
  "hello, snakemake"
}
"""
    == """
    hello, snakemake
"""
)

if 1:
    assert (
        f"""
{
  "hello, snakemake"
}
"""
        == """
hello, snakemake
"""
    )

assert f"FORMAT['{PREFIX}']['{{}}']" == "FORMAT['SID23454678']['{}']"
assert f"FORMAT['{PREFIX}'][}}'{{'{{]" == "FORMAT['SID23454678'][}'{'{]"
