shell.executable("bash")

PREFIX = "SID23454678"


rule unit1:
    output:
        f"{PREFIX}.txt",
    shell:
        "echo '>'{output}'<'; touch {output}; sleep 1"


assert (
    f"""
{
  "hello, snakemake"
}
"""
    == """
hello, snakemake
"""
)
assert (
    f"""
    {
  "hello, snakemake"
}
"""
    == """
    hello, snakemake
"""
)

if 1:
    assert (
        f"""
{
  "hello, snakemake"
}
"""
        == """
hello, snakemake
"""
    )
