

rule a:
    input:
        "test.txt"
    output:
        "test.out"
    singularity:
        "shub://vsoch/hello-world@e279432e6d3962777bb7b5e8d54f30f4347d867e"
    shell:
        'ls {input}; /rawr.sh > {output}; echo "test" >> {output}'


rule b:
    output:
        "test.txt"
    shell:
        "touch {output}"
