container: "docker://master_image"


module test:
    snakefile:
        "module.smk"


use rule * from test


rule all:
    input:
        "result.txt",
    output:
        "final.txt"
    shell:
        "echo master > {output}"
