import os

rule all:
    input:
        expand("test/{sample}.tsv", sample=range(3))

rule a:
    input:
        os.environ["UNIT_TEST_TMPFILE"]
    output:
        temp("test/{sample}.txt")
    shell:
        "touch {output}"


rule b:
    input:
        "test/{sample}.txt"
    output:
        "test/{sample}.tsv"
    shell:
        "cp {input} {output}"
