pathvars:
    output="output",


rule all:
    input:
        "<output>/result.txt",


rule a:
    input:
        "input.txt",
    output:
        "<output>/result.txt",
    shell:
        "cp {input} {output}"
