from snakemake.remote import GS
GS = GS.RemoteProvider()


rule copy:
    input:
        GS.remote("gcp-public-data-landsat/LC08/01/001/003/LC08_L1GT_001003_20170430_20170501_01_RT/LC08_L1GT_001003_20170430_20170501_01_RT_MTL.txt")
    output:
        # This output file is already present because we cannot download in CI without authentication.
        # However, we can check the mtime at least, which is what this test does.
        "landsat-data.txt"
    shell:
        "cp {input} {output}"

