def conda_func(wildcards, params):
    shell(
        f"source activate base; mamba create -y -n {params.name_prefix}-test-env -c conda-forge --override-channels ripgrep=={wildcards.version}"
    )
    return f"{params.name_prefix}-test-env"


onsuccess:
    shell("conda env remove -y -n foo-test-env")


onerror:
    shell("conda env remove -y -n foo-test-env")


rule all:
    input:
        "test_13.0.0_v.out",
        "test_12.1.1_v.out",


rule a:
    output:
        "test_{version}_v.out",
    params:
        name_prefix="foo",
    conda:
        conda_func
    shell:
        r"rg --version | head -n1 | grep -o 'ripgrep [0-9]*\.[0-9]*\.[0-9]*' > {output}"
