
DATASETS = "adhesome".split()

rule all:
	input: "{ds}/matches.html".format(ds=ds) for ds in DATASETS 

rule fetch_pmids:
	input: "{ds}/proteins.txt"
	output: "{ds}/pmids.txt"
	shell: "pubfetcher.py --nodownload --minfound 3 --searchitems {input} > {output}"

rule merge_pmids:
	input: "{ds}/pmids.txt".format(ds=ds) for ds in DATASETS
	output: "all.pmids.txt"
	shell: "cat {input} > {output}"

rule fetch_pdfs:
	input: "all.pmids.txt"
	output: "pdfs"
	shell: "pubfetcher.py --pmids {input} --output {output}"

rule tokenize:
        input: pdfs="pdfs", tokens="{ds}/tokens.txt"
        output: "{ds}/tokenized"
        shell:
                """
                mkdir -p {output}
                trminer -j40 -s {output} -t {tokens} --tokenize {input.pdfs}/*/*.pdf
                """

rule mine:
        input: tokenized = "{ds}/tokenized", pdfs = "pdfs", tokens="{ds}/tokens.txt", patterns="{ds}/patterns.txt"
        output: "{ds}/matches.html"
        shell: "trminer -j40 -s {input.tokenized} -t {tokens} -p {patterns} -o {output} --mine {input.pdfs}/*/*.pdf"
