
rule rule1:
	input: 'test.inter'
	output: 'test.out'
	#message: 'Copying {input[0]} to {output[0]}'
	shell: 
		'cp {input[0]} {output[0]}'

rule rule2:
	input: 'test.in'
	output: temp('test.inter')
	#message: 'Copying {input[0]} to {output[0]}'
	shell:
		'cp {input[0]} {output[0]}'
