# snakemake

rule all:
	input: dynamic("test.{n}.out"), "test.txt"
	run:
		pass

rule inter:
	input: "test.{n}.inter"
	output: "test.{n}.out"
	shell: "cp {input} {output}"

rule dynoutput:
	input: "test.in"
	output: dynamic("test.{n}.inter")
	shell: "for i in {{0..2}}; do touch test.$i.inter; done"

rule:
	input: dynamic("test.{n}.inter")
	output: "test.txt"
	shell: "touch test.txt"
