rule all:
	input: 'test.bla.out', 'test.blub.out'

rule wildcards:
	input: 'test.in'
	output: 'test.{xyz}.out'
	message: 'Creating file {output[0]}, xyz={wildcards.xyz}'
	threads: 2
	shell: 'sleep 5; echo {wildcards.xyz} > {output[0]}'
