from snakemake.utils import min_version

min_version("6.1.1")

configfile: "config.yaml"

import os

module_path = os.path.join(os.getcwd(), "repo/module")

module local_git_module:
    snakefile:
        gitfile(module_path, path="workflow/Snakefile", tag="v0.0.1")
    config:
        config

use rule * from local_git_module as local_git_module_*

rule all:
    input:
        "test.txt"
