onsuccess:
    shell("echo {log}")

rule all:
    input:
        expand("results/{i}.txt", i=range(5)),


rule a:
    output:
        "results/{i}.txt",
    params:
        value=lambda wildcards: wildcards.i,
    shell:
        "echo {wildcards.i} > {output}"
