# vim: syntax=python
#

# this workflow is taken from tibanna as a simple testing example
# step1 and step1a are grouped. step1b must run concurrently with step1+step1a.
# step2 waits for step1, step1a and step1b to finish.
# all is the final rule.
# step1, step1a and step1b use a conda environment.
# Input of step1, step1b and all are set remote.
# Output of step2 is set remote.

from snakemake.remote.GS import RemoteProvider as GSRemoteProvider
GS = GSRemoteProvider()

# These files will be uploaded to Google Cloud Storage at the end
rule all:
    input:
        final = GS.remote("snakemake-testing/1/final_message"),
        final2 = GS.remote("snakemake-testing/1/copied_message")


# Step 1 will echo the content of an uploaded file to message1
rule step1:
    conda:
        "env.yml"
    group: "mygroup"
    input:
        GS.remote("snakemake-testing/scripts/avocados.txt")
    output:
        message = "message1"
    shell:
        """
        echo {config[message]} > message1
        cat snakemake-testing/scripts/avocados.txt >> message1
        """

rule step1a:
    conda:
        "env.yml"
    group: "mygroup"
    input:
        message = "message1"
    output:
        next_message = "next_message"
    shell:
        """
        cat message1 message1 > next_message
        """

rule step1b:
    conda:
        "env.yml"
    input:
        GS.remote("snakemake-testing/scripts/tacos.txt")
    output:
        message = "message2"
    log:
        "log.txt"
    benchmark:
        "benchmark.txt"
    threads: 1
    resources:
        mem_mb=1024
    shell:
        """
        echo "abcdefg" > message2
        cat snakemake-testing/scripts/tacos.txt >> message2
        """

rule step2:
    input:
        message1 = "next_message",
        message2 = "message2"
    output:
        final = GS.remote("snakemake-testing/1/final_message"),
        # final = "snakemake-tibanna-test/1/final_message"
        final2 = GS.remote("snakemake-testing/1/copied_message")
    script:
        "scripts/step2.py"
