from snakemake.remote.zenodo import RemoteProvider
import os

ZEN = RemoteProvider(access_token=os.environ["ZENODO_SANDBOX_PAT"], sandbox=True)

rule all:
    input: ZEN.remote("upload.txt"), "download.txt"

rule download:
    input:
        ZEN.remote("upload.txt")
    output:
        "download.txt"
    shell:
        "cp {input} {output}"

rule upload:
    output: ZEN.remote("upload.txt")
    shell: "touch {output}"
