import os.path

subworkflow test02:
    workdir: config["subworkdir"]
    configfile: "subconfig.yaml" # test optional config files

rule:
    input: "test.out"

rule:
    input: test02("test.out")
    output: "test.out"
    shell: "cp {input} {output}"
