import os.path

subworkflow test02:
    workdir: config["subworkdir"]
    configfile: "subconfig.yaml" # test optional config files

rule:
    input: "test.out"


def test_in(wildcards):
    return test02("test.out")


rule:
    input: test_in
    output: "test.out"
    shell: "cp {input} {output}"
