shell.executable("bash")

import pandas as pd
from snakemake.utils import validate


configfile: "config.yaml"


validate(config, "config.schema.yaml")

samples = pd.read_table(config["samples"]).set_index("sample", drop=False)
validate(samples, "samples.schema.yaml")


rule all:
    input:
        expand("test.{sample}.txt", sample=samples.index),


module test:
    snakefile:
        "module-test/Snakefile"
    config:
        config


use rule * from test as test_*
