rule all:
  input:
    multiext("a", ".1", ".2"),
    multiext("b", out1 = ".1", out2 = ".2")

rule a:
    output:
        multiext("a", ".1", ".2"),
    shell:"""
        touch a.1
        touch a.2
    """

rule b:
    output:
        multiext("b", out1 = ".1", out2 = ".2"),
    shell:"""
        touch {output.out1}
        touch {output.out2}
    """