rule joint_all:
    input:
        "test_final_b.txt",

rule a_1:
    input:
        "test1a.txt"
    output:
        "test_intermediate1.txt"
    shell:
        "cat {input}  > {output}"

rule a_2:
    input:
        "test1b.txt"
    output:
        "test_intermediate2.txt"
    shell:
        "cat {input}  > {output}"

rule b:
    input:
        "test_intermediate1.txt", "test_intermediate2.txt"
    output:
        "test_final_b.txt"
    shell:
        "cat {input} > {output}"
