shell.executable("bash")

rule:
	input: "test.in"
	output: "test.out"
	run:
		test = shell("echo 42;", read=True)
		assert int(test) == 42
		with open(output[0], "w") as f:
			for l in shell("cat {input}", iterable=True):
				print(l, file=f)
