rule all:
    input:
        'result_final.Notebook.txt'

rule foo:
    output:
        fname = 'data.txt'
    run:
        with open(output.fname, 'w') as fd:
            fd.write('result of serious computation')

rule bar:
    input:
        infile = 'data.txt'
    output:
        outfile = 'result_intermediate.{notebook}.txt'
    conda:
        'env.yaml'
    notebook:
        '{wildcards.notebook}.ipynb'

rule baz:
    input:
        infile = 'result_intermediate.{notebook}.txt'
    output:
        outfile = 'result_final.{notebook}.txt'
    log:
        notebook = 'Notebook_Processed.{notebook}.ipynb'
    conda:
        'env.yaml'
    notebook:
        '{wildcards.notebook}.ipynb'
