rule all:
    input:
        'result_final.txt'

rule foo:
    output:
        fname = 'data.txt'
    run:
        with open(output.fname, 'w') as fd:
            fd.write('result of serious computation')

rule bar:
    input:
        infile = 'data.txt'
    output:
        outfile = 'result_intermediate.txt'
    notebook:
        'Notebook.ipynb'

rule baz:
    input:
        infile = 'result_intermediate.txt'
    output:
        notebook_output = 'Notebook_Processed.ipynb',
        outfile = 'result_final.txt'
    notebook:
        'Notebook.ipynb'
