scattergather:
    # Will be overridden to split=6 via CLI, effectively raising allowed max_failures to 3.
    split={"items": 4, "tolerance": 0.5}


rule all:
    input:
        "gathered/all.txt"


rule split:
    output:
        scatter.split("splitted/{scatteritem}.txt")
    shell:
        r"""
        mkdir -p splitted
        for output in {output}; do
            printf '%s\n' "$output" | sed 's#^splitted/##; s#\.txt$##' > "$output"
        done
        """


rule intermediate:
    input:
        "splitted/{scatteritem}.txt"
    output:
        "splitted/{scatteritem}.post.txt"
    shell:
        r"""
        # Fail exactly 3 branches.
        # Since CLI overrides split=6, 3 failures out of 6 should be exactly 50%
        # allowed tolerance.
        case "{input}" in
            *2-of-*.txt|*4-of-*.txt|*6-of-*.txt)
                exit 1
                ;;
        esac
        cp {input} {output}
        """


rule gather:
    input:
        gather.split("splitted/{scatteritem}.post.txt")
    output:
        "gathered/all.txt"
    shell:
        "mkdir -p gathered && cat {input} > {output}"
