import os.path
import sys

instances = [os.path.basename(s[:len(s)-4]) for s in os.listdir('mfa') if s.endswith('.mfa')]

rule all:
	input: ['fisher/%s.pairs.gz'%s for s in instances] + ['ph/%s.ph'%s for s in instances]

rule extract_mismatch_counts:
	input: 'mfa/{instance}.mfa'
	output: 'fisher/{instance}.pairs.gz'
	message: 'Extracting number mismatches for each pair of sequences from {input}'
	shell: 'sleep 2; touch {output}'

rule create_tree:
	input: 'mfa/{instance}.mfa'
	output: 'ph/{instance}.ph', 'ph/{instance}.ph.log'
	message: 'Running CLUSTALW to compute NJ tree from {input}'
	shell: "sleep 2; touch {output[0]}; touch {output[1]}"
