rule all:
    output: 
        "results/output.txt"
    input:
        "results/intermediate.txt"
    shell:
        "touch {output}"


module minimal_module:
    snakefile:
        github(
            "snakemake/snakemake", 
            path="tests/test_python_import_from_github_module/minimal_module/Snakefile", 
            commit="a47b89fb83125018c84cceca44e95780e968322d"
        )

use rule * from minimal_module