part_one = "foo"
an_fstring = f'{part_one}/{"bar" if True else "baz"}'
another_fstring = f"{part_one.replace('foo', 'bar')}/{{escaped}}"
multiple_parts_fstring = f"no_replacement_" "regular_string_" f"{'bar' if True else 'baz'}"

rule:
    output: 
        first=an_fstring,
        second=expand(another_fstring, escaped=["baz"]),
        third=multiple_parts_fstring,
    shell:
        """
        touch {output.first}
        touch {output.second}
        touch {output.third}
        """


