rule all:
    input:
        expand("test{i}.out", i=range(3))

rule a:
    output:
        "test{i}.out"
    conda:
        "test-env.yaml"
    shell:
        "(test -d custom/conda/6291eeeb63ef1987c7d7fa4494eb56d6 ||"
        " test -d custom/conda/6291eeeb)"
        " && snakemake --version > {output}"
