rule random_python_conda_script:
    output:
        "test.txt"
    conda:
        "test_python_env.yaml"
    params: 
        script=workflow.source_path('test_script_run.py')
    run:
        shell("python {params.script}")
