shell.executable("bash")


configfile: "config.yaml"


rule all:
    input:
        "test.out",
        "explicit_import.py.out",
        "cli_args.out"


rule:
    output:
        "test.out",
    script:
        "scripts/test.py"


rule:
    output:
        "explicit_import.py.out",
    script:
        "scripts/test_explicit_import.py"

rule:
    output:
        "cli_args.out",
    script:
        "scripts/test_cli_args.py test"
