from snakemake.utils import min_version

min_version("6.0")

configfile: "config.yaml"

remote_workflow_directory = "https://raw.githubusercontent.com/snakemake-workflows/dna-seq-varlociraptor/v5.0.2"
workflow_snakefile = f"{remote_workflow_directory}/workflow/Snakefile"


# basic
## use basic workflow
module basic:
    snakefile:
        workflow_snakefile
    replace_prefix:
        {
            "benchmarking/": "benchmarking/basic/",
            "logs/": "logs/basic/",
            "results/": "results/basic/",
        }
    config:
        config


use rule * from basic as basic_*


rule all:
    input:
        rules.basic_all.input
