
rule html:
    input:
        rst="snakemake-tutorial.rst",
        style="style.css",
        bstrap="bootstrap.css"
    output:
        "snakemake-tutorial.html"
    shell:
        "pandoc --self-contained -s -S --toc-depth 2 -f rst "
        "-c {input.bstrap} -c {input.style} -t html5 "
        "{input.rst} -o {output}"
