target = list('ankles')
word = 'snake'
for i in word:
    print(word.index(i) + 1)

rule all:
    input: expand('{i}.out', i=target)

rule echo:
    output: '{i}.out'
    priority: lambda wc:  word.index(wc.i) + 1  if wc.i in word else 0
    shell: 'echo {wildcards.i} > {output} && echo {wildcards.i} >> order.out'

rule a:
    output: 'a.out'
    priority: 50
    shell: 'echo a > a.out && echo a >> order.out'