configfile: "config.yaml" # does not exist, but this statement should be ignored on module import


def some_func():
    return 15


rule all:
    input:
        "results/test.out", "results/test2.out"


rule a:
    output:
        "results/test.out"
    shell:
        "echo {config[test]} > {output}"

rule b:
    output:
        "results/test2.out"
    shell:
        "echo {config[testb]} > {output}"

rule c:
    output:
        "results/test2.out"
    shell:
        "echo {config[testc]} > {output}"

rule d:
    output:
        "results/test2.out"
    shell:
        "echo {config[testc]} > {output}"
